
CREATE TABLE IF NOT EXISTS branding (
  id SERIAL PRIMARY KEY,
  name varchar(80) NOT NULL DEFAULT 'Foxnox',
  tagline varchar(160) NOT NULL DEFAULT 'Account security',
  "logoUrl" varchar(2048) NOT NULL DEFAULT '',
  "logoAlt" varchar(120) NOT NULL DEFAULT '',
  mark varchar(2) NOT NULL DEFAULT 'F',
  "primaryColor" varchar(7) NOT NULL DEFAULT '#1f6feb',
  "secondaryColor" varchar(7) NOT NULL DEFAULT '#5c6570',
  "primaryHoverColor" varchar(7) NOT NULL DEFAULT '#1858c3',
  "backgroundColor" varchar(7) NOT NULL DEFAULT '#f4f6f8',
  "footerText" varchar(240) NOT NULL DEFAULT '',
  "footerUrl" varchar(2048) NOT NULL DEFAULT '',
  "fontFamily" varchar(20) NOT NULL DEFAULT 'system',
  radius varchar(6) NOT NULL DEFAULT '12px',
  archived BOOLEAN DEFAULT FALSE,
  "archivedAt" TIMESTAMPTZ DEFAULT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "creatorId" INT,
  "creatorName" TEXT,
  "updatedAt" TIMESTAMPTZ NULL,
  "updaterId" INT,
  "updaterName" TEXT,
  CHECK ("primaryColor" ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$'),
  CHECK ("secondaryColor" ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$'),
  CHECK ("primaryHoverColor" ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$'),
  CHECK ("backgroundColor" ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$'),
  CHECK ("fontFamily" IN ('system', 'serif', 'mono')),
  CHECK (radius ~ '^([0-9]|1[0-9]|2[0-4])px$')
);
