// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

/**
 * Read-only entity over the log.audit view (db/liquibase/foxnox/versions/04-view/02-audit.sql).
 * `record` and `previous` carry raw row snapshots, so they are private: the
 * audit mapper turns them into redacted `changes` before `send` strips them.
 */
export default new SQLEntity(
  "audit",
  [
    {
      key: "id",
      type: "integer",
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "tstamp",
      type: "date",
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "tableName",
      type: "string",
      min: 1,
      max: 100,
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "operation",
      type: "string",
      min: 1,
      max: 20,
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "action",
      type: "string",
      min: 1,
      max: 20,
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "userId",
      type: "integer",
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "userName",
      type: "string",
      min: 1,
      max: 100,
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "recordId",
      type: "integer",
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "changedKeys",
      type: "array",
      isTypeChecked: false,
      isFilterable: false,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: true,
      readOnly: true,
    },
    {
      key: "kind",
      type: "string",
      min: 1,
      max: 20,
      isTypeChecked: true,
      isFilterable: true,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: false,
      readOnly: true,
    },
    {
      key: "record",
      type: "object",
      isTypeChecked: false,
      isFilterable: false,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: true,
      readOnly: true,
    },
    {
      key: "previous",
      type: "object",
      isTypeChecked: false,
      isFilterable: false,
      requiredFor: [],
      operations: ["SELECT"],
      isPrivate: true,
      readOnly: true,
    },
  ],
  "log",
);
