// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("branding", [
  {
    key: "id",
    type: "integer",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "name",
    type: "string",
    min: 1,
    max: 80,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "tagline",
    type: "string",
    min: 0,
    max: 160,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "logoUrl",
    type: "string",
    min: 0,
    max: 2048,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "logoAlt",
    type: "string",
    min: 0,
    max: 120,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "mark",
    type: "string",
    min: 0,
    max: 2,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "primaryColor",
    type: "string",
    min: 4,
    max: 7,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "secondaryColor",
    type: "string",
    min: 4,
    max: 7,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "primaryHoverColor",
    type: "string",
    min: 4,
    max: 7,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "backgroundColor",
    type: "string",
    min: 4,
    max: 7,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "footerText",
    type: "string",
    min: 0,
    max: 240,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "footerUrl",
    type: "string",
    min: 0,
    max: 2048,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "fontFamily",
    type: "string",
    min: 1,
    max: 20,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "radius",
    type: "string",
    min: 2,
    max: 6,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "archived",
    type: "boolean",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "archivedAt",
    type: "date",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "createdAt",
    type: "date",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "creatorName",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "updatedAt",
    type: "date",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "updaterName",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
]);
