// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("preferences", [
  {
    key: "id",
    type: "integer",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "userId",
    type: "integer",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT"],
    isPrivate: true,
    readOnly: false,
  },
  {
    key: "resourceName",
    type: "string",
    min: 1,
    max: 20,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "name",
    type: "string",
    min: 1,
    max: 60,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT", "POST"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "conf",
    type: "object",
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    normalizer: JSON.stringify,
    readOnly: false,
  },
  {
    key: "locked",
    type: "boolean",
    isTypeChecked: false,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "isActive",
    type: "boolean",
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: ["PUT", "POST"],
    operations: ["INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
]);
