// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";
import { dedupeSymbols } from "../utils/pwd-symbols.js";

// ASCII punctuation only (no letters, digits or whitespace), max 50 chars.
// Must stay in sync with the admin policy form (policy.conf.ts) and the
// pwd_policy CHECK on `symbols` (db/liquibase/foxnox/versions/03-struct/02-pwd-policy.sql).
const SYMBOLS_RE = /^[!-/:-@[-`{-~]{0,50}$/;

export default new SQLEntity("pwd_policy", [
  {
    key: "id",
    type: "integer",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "name",
    type: "string",
    min: 1,
    max: 50,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "description",
    type: "string",
    min: 0,
    max: 100,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "length",
    type: "integer",
    min: 6,
    max: 64,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "number",
    type: "boolean",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "symbol",
    type: "boolean",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "lowerCase",
    type: "boolean",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "upperCase",
    type: "boolean",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "strict",
    type: "boolean",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "symbols",
    type: "string",
    min: 0,
    max: 50,
    isTypeChecked: true,
    normalizer: dedupeSymbols,
    validator: (/** @type {unknown} */ v) =>
      typeof v === "string" && SYMBOLS_RE.test(v),
    isFilterable: true,
    requiredFor: ["PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "expiryDays",
    type: "integer",
    min: 0,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "maxFailedAttempts",
    type: "integer",
    min: 1,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "lockoutMinutes",
    type: "integer",
    min: 0,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "archived",
    type: "boolean",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "archivedAt",
    type: "date",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: true,
  },
  {
    key: "createdAt",
    type: "date",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: true,
  },
  {
    key: "creatorName",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "updatedAt",
    type: "date",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: true,
  },
  {
    key: "updaterName",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
]);
