// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("token", [
  {
    key: "id",
    type: "integer",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "hash",
    type: "string",
    min: 0,
    max: 255,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: [],
    operations: ["INSERT"],
    isPrivate: true,
    readOnly: false,
  },
  {
    key: "typeId",
    type: "integer",
    min: 1,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "userId",
    type: "integer",
    min: 1,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "attempts",
    type: "integer",
    min: 0,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "archived",
    type: "boolean",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "archivedAt",
    type: "date",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: true,
  },
  {
    key: "createdAt",
    type: "date",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: true,
  },
  {
    key: "creatorName",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "updatedAt",
    type: "date",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: true,
  },
  {
    key: "updaterName",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "expiresAt",
    type: "date",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
  {
    key: "verifiedAt",
    type: "date",
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT", "UPDATE"],
    isPrivate: false,
    readOnly: false,
  },
]);
