name: ${APP_NAME}

secrets:
  apk_repository:
    environment: APK_REPOSITORY
  npmrc:
    environment: NPMRC

services:
  admin:
    build:
      context: ${PWD}/admin
      dockerfile: dockerfile.prod
      secrets:
        - apk_repository
        - npmrc
      args:
        NODE_VERSION: ${NODE_VERSION}
        CADDY_VERSION: ${CADDY_VERSION}
        ADMIN_PORT: ${ADMIN_PORT}
        TZ: ${TZ}
        UID: ${UID}
        GID: ${GID}
        NPMRC_PATH: ${HOME_PATH}.npmrc
    image: dwtechs/foxnox-admin:${VERSION:-latest}
    container_name: ${ADMIN_HOST}
    hostname: ${ADMIN_HOST}
    environment:
      ADMIN_PORT: ${ADMIN_PORT}
      ADMIN_SSO_TOKEN_KEY: ${ADMIN_SSO_TOKEN_KEY:-}
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "stack.name=${STACK_NAME}"
      - "traefik.http.routers.admin.rule=PathPrefix(`/foxnox`)"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.routers.admin.service=admin"
      - "traefik.http.services.admin.loadbalancer.server.port=${ADMIN_PORT}"

networks:
  internal:
    name: ${APP_NAME}-internal-${ENV_NAME}
    driver: bridge
