// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("password_policies", [
  {
    key: "id",
    type: "integer",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT", "DELETE"],
    operations: ["SELECT", "UPDATE", "DELETE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "appId",
    type: "integer",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "appName",
    type: "string",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "name",
    type: "string",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "description",
    type: "string",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "length",
    type: "integer",
    min: 6,
    max: 64,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "number",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "symbol",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "lowerCase",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "upperCase",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "strict",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "symbols",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "expiryDays",
    type: "integer",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "archived",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "archivedAt",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "createdAt",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "updatedAt",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
]);