// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("pwd", [
    {
    key: "id",
    type: "integer",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "POST"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "userId",
    type: "integer",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "POST"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "pwdHash",
    type: "password",
    min: null,
    max: null,
    typeCheck: false,
    filter: false,
    methods: ["POST"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    required: true,
    safe: false,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "pwdResetToken",
    type: "string",
    min: 0,
    max: 150,
    typeCheck: true,
    filter: false,
    methods: ["PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: false,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "pwdUpdatedAt",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "pwdExpiry",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "failedAttempts",
    type: "integer",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "lockedUntil",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "lastLoginAt",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "twoFactorEnabled",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "twoFactorSecret",
    type: "string",
    min: 0,
    max: 255,
    typeCheck: true,
    filter: false,
    methods: ["PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: false,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "recoveryToken",
    type: "string",
    min: 0,
    max: 255,
    typeCheck: true,
    filter: false,
    methods: ["PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: false,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "recoveryTokenExpiresAt",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "archived",
    type: "boolean",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET", "PUT"],
    operations: ["SELECT", "UPDATE"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "archivedAt",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "createdAt",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
  {
    key: "updatedAt",
    type: "timestamp",
    min: 0,
    max: 999999999,
    typeCheck: true,
    filter: true,
    methods: ["GET"],
    operations: ["SELECT"],
    required: true,
    safe: true,
    sanitize: true,
    normalize: false,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null
  },
]);
