--
-- Locked table-view templates used by the Foxnox admin.
-- Personal copies and the active selection remain owned by Gatelin.
--

INSERT INTO preference ("resourceId", name, conf, "creatorId", "creatorName") VALUES

-- passwords
((SELECT id FROM resource WHERE name = 'passwords'), 'Default', '[
  {"key":"id",               "isVisible":false},
  {"key":"userId",           "isVisible":true,  "defaultWidth":"80px"},
  {"key":"pwdHash",          "isVisible":false},
  {"key":"pwdUpdatedAt",     "isVisible":true},
  {"key":"pwdExpiry",        "isVisible":true},
  {"key":"failedAttempts",   "isVisible":true},
  {"key":"lockedUntil",      "isVisible":true},
  {"key":"lastLoginAt",      "isVisible":true},
  {"key":"twoFactorEnabled", "isVisible":true,  "defaultWidth":"80px"},
  {"key":"twoFactorSecret",  "isVisible":false},
  {"key":"createdAt",        "isVisible":false},
  {"key":"creatorName",      "isVisible":false},
  {"key":"updatedAt",        "isVisible":false},
  {"key":"updaterName",      "isVisible":false},
  {"key":"archived",         "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",       "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'passwords'), 'Compact', '[
  {"key":"id",               "isVisible":false},
  {"key":"userId",           "isVisible":true,  "defaultWidth":"80px"},
  {"key":"pwdHash",          "isVisible":false},
  {"key":"pwdUpdatedAt",     "isVisible":false},
  {"key":"pwdExpiry",        "isVisible":false},
  {"key":"failedAttempts",   "isVisible":true},
  {"key":"lockedUntil",      "isVisible":true},
  {"key":"lastLoginAt",      "isVisible":true},
  {"key":"twoFactorEnabled", "isVisible":true,  "defaultWidth":"80px"},
  {"key":"twoFactorSecret",  "isVisible":false},
  {"key":"createdAt",        "isVisible":false},
  {"key":"creatorName",      "isVisible":false},
  {"key":"updatedAt",        "isVisible":false},
  {"key":"updaterName",      "isVisible":false},
  {"key":"archived",         "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",       "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'passwords'), 'Archives', '[
  {"key":"id",               "isVisible":false},
  {"key":"userId",           "isVisible":true,  "defaultWidth":"80px"},
  {"key":"pwdHash",          "isVisible":false},
  {"key":"pwdUpdatedAt",     "isVisible":false},
  {"key":"pwdExpiry",        "isVisible":true},
  {"key":"failedAttempts",   "isVisible":false},
  {"key":"lockedUntil",      "isVisible":true},
  {"key":"lastLoginAt",      "isVisible":true},
  {"key":"twoFactorEnabled", "isVisible":true,  "defaultWidth":"80px"},
  {"key":"twoFactorSecret",  "isVisible":false},
  {"key":"createdAt",        "isVisible":false},
  {"key":"creatorName",      "isVisible":false},
  {"key":"updatedAt",        "isVisible":false},
  {"key":"updaterName",      "isVisible":false},
  {"key":"archived",         "isVisible":true,  "defaultWidth":"60px"},
  {"key":"archivedAt",       "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'passwords'), 'Audit', '[
  {"key":"id",               "isVisible":false},
  {"key":"userId",           "isVisible":true,  "defaultWidth":"80px"},
  {"key":"pwdHash",          "isVisible":false},
  {"key":"pwdUpdatedAt",     "isVisible":true},
  {"key":"pwdExpiry",        "isVisible":false},
  {"key":"failedAttempts",   "isVisible":false},
  {"key":"lockedUntil",      "isVisible":false},
  {"key":"lastLoginAt",      "isVisible":false},
  {"key":"twoFactorEnabled", "isVisible":false, "defaultWidth":"80px"},
  {"key":"twoFactorSecret",  "isVisible":false},
  {"key":"createdAt",        "isVisible":true},
  {"key":"creatorName",      "isVisible":true},
  {"key":"updatedAt",        "isVisible":true},
  {"key":"updaterName",      "isVisible":true},
  {"key":"archived",         "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",       "isVisible":false}
]', -1, 'system'),

-- policies
((SELECT id FROM resource WHERE name = 'policies'), 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"length",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"number",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"symbol",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"lowerCase",   "isVisible":true,  "defaultWidth":"80px"},
  {"key":"upperCase",   "isVisible":true,  "defaultWidth":"80px"},
  {"key":"strict",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"symbols",     "isVisible":false},
  {"key":"expiryDays",  "isVisible":true,  "defaultWidth":"80px"},
  {"key":"active",      "isVisible":true,  "defaultWidth":"60px"},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'policies'), 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"length",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"number",      "isVisible":false, "defaultWidth":"80px"},
  {"key":"symbol",      "isVisible":false, "defaultWidth":"80px"},
  {"key":"lowerCase",   "isVisible":false, "defaultWidth":"80px"},
  {"key":"upperCase",   "isVisible":false, "defaultWidth":"80px"},
  {"key":"strict",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"symbols",     "isVisible":false},
  {"key":"expiryDays",  "isVisible":true,  "defaultWidth":"80px"},
  {"key":"active",      "isVisible":true,  "defaultWidth":"60px"},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'policies'), 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"length",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"number",      "isVisible":false, "defaultWidth":"80px"},
  {"key":"symbol",      "isVisible":false, "defaultWidth":"80px"},
  {"key":"lowerCase",   "isVisible":false, "defaultWidth":"80px"},
  {"key":"upperCase",   "isVisible":false, "defaultWidth":"80px"},
  {"key":"strict",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"symbols",     "isVisible":false},
  {"key":"expiryDays",  "isVisible":true,  "defaultWidth":"80px"},
  {"key":"active",      "isVisible":true,  "defaultWidth":"60px"},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true,  "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'policies'), 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"length",      "isVisible":false, "defaultWidth":"80px"},
  {"key":"number",      "isVisible":false, "defaultWidth":"80px"},
  {"key":"symbol",      "isVisible":false, "defaultWidth":"80px"},
  {"key":"lowerCase",   "isVisible":false, "defaultWidth":"80px"},
  {"key":"upperCase",   "isVisible":false, "defaultWidth":"80px"},
  {"key":"strict",      "isVisible":false, "defaultWidth":"80px"},
  {"key":"symbols",     "isVisible":false},
  {"key":"expiryDays",  "isVisible":false, "defaultWidth":"80px"},
  {"key":"active",      "isVisible":false, "defaultWidth":"60px"},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),

-- tokens
((SELECT id FROM resource WHERE name = 'tokens'), 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"typeId",      "isVisible":true},
  {"key":"userId",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"attempts",    "isVisible":true,  "defaultWidth":"80px"},
  {"key":"expiresAt",   "isVisible":true},
  {"key":"verifiedAt",  "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'tokens'), 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"typeId",      "isVisible":true},
  {"key":"userId",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"attempts",    "isVisible":false, "defaultWidth":"80px"},
  {"key":"expiresAt",   "isVisible":true},
  {"key":"verifiedAt",  "isVisible":false},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'tokens'), 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"typeId",      "isVisible":true},
  {"key":"userId",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"attempts",    "isVisible":false, "defaultWidth":"80px"},
  {"key":"expiresAt",   "isVisible":true},
  {"key":"verifiedAt",  "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true,  "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'tokens'), 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"typeId",      "isVisible":true},
  {"key":"userId",      "isVisible":true,  "defaultWidth":"80px"},
  {"key":"attempts",    "isVisible":false, "defaultWidth":"80px"},
  {"key":"expiresAt",   "isVisible":false},
  {"key":"verifiedAt",  "isVisible":false},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),

-- trusted devices
((SELECT id FROM resource WHERE name = 'trustedDevices'), 'Default', '[
  {"key":"id",              "isVisible":false},
  {"key":"userId",          "isVisible":true,  "defaultWidth":"80px"},
  {"key":"deviceTokenHash", "isVisible":false},
  {"key":"deviceName",      "isVisible":true},
  {"key":"ipAddress",       "isVisible":true},
  {"key":"userAgent",       "isVisible":false},
  {"key":"expiresAt",       "isVisible":true},
  {"key":"lastUsedAt",      "isVisible":true},
  {"key":"createdAt",       "isVisible":false},
  {"key":"creatorName",     "isVisible":false},
  {"key":"updatedAt",       "isVisible":false},
  {"key":"updaterName",     "isVisible":false},
  {"key":"archived",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",      "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'trustedDevices'), 'Compact', '[
  {"key":"id",              "isVisible":false},
  {"key":"userId",          "isVisible":true,  "defaultWidth":"80px"},
  {"key":"deviceTokenHash", "isVisible":false},
  {"key":"deviceName",      "isVisible":true},
  {"key":"ipAddress",       "isVisible":false},
  {"key":"userAgent",       "isVisible":false},
  {"key":"expiresAt",       "isVisible":true},
  {"key":"lastUsedAt",      "isVisible":true},
  {"key":"createdAt",       "isVisible":false},
  {"key":"creatorName",     "isVisible":false},
  {"key":"updatedAt",       "isVisible":false},
  {"key":"updaterName",     "isVisible":false},
  {"key":"archived",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",      "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'trustedDevices'), 'Archives', '[
  {"key":"id",              "isVisible":false},
  {"key":"userId",          "isVisible":true,  "defaultWidth":"80px"},
  {"key":"deviceTokenHash", "isVisible":false},
  {"key":"deviceName",      "isVisible":true},
  {"key":"ipAddress",       "isVisible":true},
  {"key":"userAgent",       "isVisible":false},
  {"key":"expiresAt",       "isVisible":true},
  {"key":"lastUsedAt",      "isVisible":true},
  {"key":"createdAt",       "isVisible":false},
  {"key":"creatorName",     "isVisible":false},
  {"key":"updatedAt",       "isVisible":false},
  {"key":"updaterName",     "isVisible":false},
  {"key":"archived",        "isVisible":true,  "defaultWidth":"60px"},
  {"key":"archivedAt",      "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'trustedDevices'), 'Audit', '[
  {"key":"id",              "isVisible":false},
  {"key":"userId",          "isVisible":true,  "defaultWidth":"80px"},
  {"key":"deviceTokenHash", "isVisible":false},
  {"key":"deviceName",      "isVisible":true},
  {"key":"ipAddress",       "isVisible":false},
  {"key":"userAgent",       "isVisible":false},
  {"key":"expiresAt",       "isVisible":false},
  {"key":"lastUsedAt",      "isVisible":false},
  {"key":"createdAt",       "isVisible":true},
  {"key":"creatorName",     "isVisible":true},
  {"key":"updatedAt",       "isVisible":true},
  {"key":"updaterName",     "isVisible":true},
  {"key":"archived",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",      "isVisible":false}
]', -1, 'system')

ON CONFLICT DO NOTHING;

ANALYZE;
